# Site settings
title: DDDevotion - Мастерство Domain-Driven Design
description: Освойте Domain-Driven Design и создавайте ПО, которое действительно решает бизнес-задачи
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dddevotion.github.io" # the base hostname & protocol for your site
lang: ru
locale: ru_RU
timezone: Europe/Moscow

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Disable default theme's footer
plugins_dir: ["_plugins", ".jekyll-cms-gem/plugins"]

# Theme settings
remote_theme: pages-themes/cayman@v0.2.0

# Add custom head includes
include:
  - _includes/head-custom.html

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor